# -*- coding: utf-8 -*-
from models.cnn import CNN
from models.clstm import CLSTM
from models.pf_cnn import PF_CNN
from models.tcn import TCN
from models.bert_pf import Bert_PF
from models.bbfc import BBFC
from models.tc_cnn import TC_CNN
from models.ram import RAM
from models.ian import IAN
from models.atae_lstm import ATAE_LSTM
from models.aoa import AOA
from models.memnet import MemNet
from models.cabasc import Cabasc
from models.tnet_lf import TNet_LF
from models.mgan import MGAN
from models.bert_ian import BERT_IAN
from models.tc_swem import TC_SWEM
from models.tt import TT
from models.mlp import MLP
from models.aen import AEN_BERT
from models.td_bert import TD_BERT
from models.td_bert_qa import TD_BERT_QA
from models.dtd_bert import DTD_BERT